#!/bin/bash

#PBS -m abe
#PBS -M mhibbins@iu.edu
#PBS -l walltime=5:00:00,vmem=16GB,nodes=1:ppn=1
#PBS -N sim_tomato_D2
#PBS -e /N/dc2/scratch/mhibbins/
#PBS -o /N/dc2/scratch/mhibbins/

#Change working directory
cd /N/dc2/scratch/mhibbins/introgression_tomato/

#Load python 3
module unload python/2.7.16
module load python/3.6.1

for i in {901..1000}
do
msdir/ms 4 7169 -t 0.000405 -T -I 4 1 1 1 1 -ej 10 2 1 -ej 2.625 3 2 -ej 0.125 4 3 -es 0.0625 2 0.997 -ej 0.0625 5 3 -en 0 2 30.74 | tail -n +4 | grep -v // >results/D2_statistic/D2_sims/D2_sims_trio5/D2_sims_trio5_trees_$i.txt
Seq-Gen-1.3.4/source/seq-gen -m HKY -l 100000 <results/D2_statistic/D2_sims/D2_sims_trio5/D2_sims_trio5_trees_$i.txt >results/D2_statistic/D2_sims/D2_sims_trio5/D2_sims_trio5_seqs_$i.txt
done
