#!/bin/bash

#PBS -m abe
#PBS -M mhibbins@iu.edu
#PBS -l walltime=40:00:00,vmem=16GB,nodes=1:ppn=1
#PBS -N sim_tomato_D2
#PBS -e /N/dc2/scratch/mhibbins/
#PBS -o /N/dc2/scratch/mhibbins/

#Change working directory
cd /N/dc2/scratch/mhibbins/introgression_tomato/

#Load python 3
module unload python/2.7.16
module load python/3.6.1

for i in {1..1000}
do
msdir/ms 4 7233 -t 0.00837 -T -I 4 1 1 1 1 -ej 50 2 1 -ej 13.125 3 2 -ej 8.75 4 3 -es 4.375 2 0.988 -ej 4.375 5 3 -en 0 2 0.0483 | tail -n +4 | grep -v // >results/D2_statistic/D2_sims/D2_sims_trio19/D2_sims_trio19_trees_$i.txt
Seq-Gen-1.3.4/source/seq-gen -m HKY -l 100000 <results/D2_statistic/D2_sims/D2_sims_trio19/D2_sims_trio19_trees_$i.txt >results/D2_statistic/D2_sims/D2_sims_trio19/D2_sims_trio19_seqs_$i.txt
done
