#!/bin/bash

#PBS -m abe
#PBS -M mhibbins@iu.edu
#PBS -l walltime=5:00:00,vmem=16GB,nodes=1:ppn=1
#PBS -N sim_tomato_D2
#PBS -e /N/dc2/scratch/mhibbins/
#PBS -o /N/dc2/scratch/mhibbins/

#Change working directory
cd /N/dc2/scratch/mhibbins/introgression_tomato/

#Load python 3
module unload python/2.7.16
module load python/3.6.1

for i in {901..1000}
do
msdir/ms 4 7163 -t 0.0027 -T -I 4 1 1 1 1 -ej 10 2 1 -ej 2.125 3 2 -ej 0.3125 4 3 -es 0.1562 2 0.988 -ej 0.1562 5 3 -en 0 2 0.15 | tail -n +4 | grep -v // >results/D2_statistic/D2_sims/D2_sims_trio16/D2_sims_trio16_trees_$i.txt
Seq-Gen-1.3.4/source/seq-gen -m HKY -l 100000 <results/D2_statistic/D2_sims/D2_sims_trio16/D2_sims_trio16_trees_$i.txt >results/D2_statistic/D2_sims/D2_sims_trio16/D2_sims_trio16_seqs_$i.txt
done
